goabase/modules/parties/urls.py
from django.conf.urls import url

from goabase.modules.parties.views import PartyListView, PartyDetailView

urlpatterns = [
    url(r'^$', PartyListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)-(?P<pk>\d+)/$', PartyDetailView.as_view(), name='detail'),
]

goabase/modules/users/urls.py
from django.conf.urls import url

from goabase.modules.users.views import (UserListView, UserRedirectView,
                                         UserDetailView, UserUpdateView)

urlpatterns = [
    url(r'^$', UserListView.as_view(), name='list'),
    url(r'^~redirect/$', UserRedirectView.as_view(), name='redirect'),
    url(r'^(?P<username>[\w.@+-]+)/$', UserDetailView.as_view(), name='detail'),
    url(r'^~update/$', UserUpdateView.as_view(), name='update'),
]

goabase/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.i18n import JavaScriptCatalog
from tastypie.api import Api

from goabase.modules.countries.api import CountryResource
from goabase.modules.parties.api import PartyResource
from goabase.modules.parties.views import PartyListView

v1_api = Api(api_name='v1')
v1_api.register(CountryResource())
v1_api.register(PartyResource())

urlpatterns = [
    url(r'^$', PartyListView.as_view(template_name='index.html'), name='index'),
    url(r'^api/', include(v1_api.urls)),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='jsi18n'),

    # Django Admin, use {% url 'admin:index' %}
    url(r'^admin/', admin.site.urls),

    # User management
    url(r'^users/', include('goabase.modules.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^parties/', include('goabase.modules.parties.urls', namespace='parties')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

goabase/core/models.py
import json
import re
import requests

from functools import reduce


def reducer(obj, init, f):
    return reduce(lambda a, b: f(a, b), obj.keys(), init)


def encode(obj):
    return re.sub(r'/-->/g', '--&gt;', json.dumps(obj))


def render_html(view_name, data):
    data = encode(data)
    return (
        '<div data-hypernova-key="{view_name}"></div>'
        '<script type="application/json" data-hypernova-key="{view_name}"><!--${data}--></script>'
    ).format(view_name=view_name, data=data)


def to_html(views):
    def callback(res, name):
        return res + views[name]['html']
    return reducer(views, '', callback)


class ReactRenderer(object):
    def __init__(self, options):
        super(ReactRenderer, self).__init__()

        self.url = options.get('url')
        self.plugins = options.get('plugins', [])

        if not isinstance(self.plugins, list):
            self.plugins = [options.get('plugins')]

        self.config = {
            'timeout': 1000,
            'headers': {'Content-Type': 'application/json'},
        }
        self.config.update(options)

    def add_plugin(self, plugin):
        self.plugins.append(plugin)

    def plugin_reduce(self, event_name, f, initial):
        def callback(res, plugin):
            if plugin[event_name]:
                return f(plugin[event_name], res)
            return res
        return reduce(callback, self.plugins, initial)

    def prepare_request(self, jobs):
        def plugin(plugin, next):
            return plugin(next, jobs)

        jobs_hash = self.plugin_reduce('prepareRequest', plugin, jobs)

        return {
            'shouldSendRequest': True,
            'jobsHash': jobs_hash,
        }

    def create_jobs(self, jobs):
        def func(obj, name):
            data = jobs[name]

            def resolve_plugin(plugin, new_data):
                return plugin(name, new_data)

            try:
                data = self.plugin_reduce('getViewData', resolve_plugin, jobs[name])
            except:
                pass

            obj[name] = {'name': name, 'data': data}

            return obj

        return reducer(jobs, {}, func)

    def render(self, data):
        jobs = self.create_jobs(data)
        prepared = self.prepare_request(jobs)

        response = requests.post(self.url, json=prepared['jobsHash'], headers=self.config['headers'])
        result = response.json()
        results = result.get('results', [])

        for job in results.values():
            if job.get('error', False):
                error = job.get('error')
                return self.plugin_reduce('onError', lambda plugin, _: plugin(error.get('message')), job)

        return to_html(results)

goabase/modules/countries/models.py
from django.contrib.gis.db import models
from django.utils.translation import ugettext_lazy as _


class Country(models.Model):
    fips = models.CharField(_('FIPS code'), max_length=2)
    iso2 = models.CharField(_('2 digit ISO'), max_length=2)
    iso3 = models.CharField(_('3 digit ISO'), max_length=3)
    un = models.IntegerField(_('United Nations code'))
    name = models.CharField(_('name'), max_length=50)
    area = models.IntegerField(_('area'))
    pop2005 = models.BigIntegerField(_('population in 2005'))
    region = models.IntegerField(_('region code'))
    subregion = models.IntegerField(_('sub-region code'))
    lon = models.FloatField(_('longitude'))
    lat = models.FloatField(_('latitude'))
    geom = models.MultiPolygonField(srid=4326, null=True)

    objects = models.GeoManager()

    class Meta:
        verbose_name = _('country')
        verbose_name_plural = _('countries')

    def __str__(self):
        return self.name


# Auto-generated `LayerMapping` dictionary for Country model
country_mapping = {
    'fips': 'FIPS',
    'iso2': 'ISO2',
    'iso3': 'ISO3',
    'un': 'UN',
    'name': 'NAME',
    'area': 'AREA',
    'pop2005': 'POP2005',
    'region': 'REGION',
    'subregion': 'SUBREGION',
    'lon': 'LON',
    'lat': 'LAT',
    'geom': 'MULTIPOLYGON',
}

goabase/modules/parties/models.py
from django.contrib.gis.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from model_utils import Choices
from scrapy_djangoitem import DjangoItem

from goabase.core.utils import slugify
from goabase.modules.countries.models import Country


class Source(models.Model):
    name = models.CharField(_('name'), max_length=50)

    class Meta:
        verbose_name = _('source')
        verbose_name_plural = _('sources')


class Party(models.Model):
    name = models.CharField(_('name'), max_length=100)
    start_date = models.DateTimeField(_('start date'))
    end_date = models.DateTimeField(_('end date'))

    TYPE_CHOICES = Choices(
        ('festival', _('Festival')),
        ('openair', _('Open Air')),
        ('indoor', _('Indoor')),
        ('club', _('Club')),
        ('indoor_outdoor', _('In- & Outdoor')),
    )
    type = models.CharField(_('type'), max_length=14, choices=TYPE_CHOICES,
                            default=TYPE_CHOICES.indoor)

    town = models.CharField(_('town'), max_length=100)
    country = models.ForeignKey(Country, verbose_name=_('country'))
    location = models.PointField(_('location'))
    lineup = models.TextField(_('lineup'))
    decoration = models.TextField(_('decoration'))
    entry_fee = models.TextField(_('entry fee'))
    more = models.TextField(_('more'))
    organizer_name = models.CharField(_('organizer name'), max_length=255)
    organizer_text = models.TextField(_('organizer text'))
    organizer_url = models.TextField(_('organizer URL'))
    image = models.ImageField(_('image'), upload_to='uploads/%Y/%m/%d/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    STATUS_CHOICES = Choices(
        ('scheduled', _('Scheduled')),
        ('cancelled', _('Cancelled')),
        ('postponed', _('Postponed')),
        ('moved', _('Moved')),
    )
    status = models.CharField(_('status'), max_length=9, choices=STATUS_CHOICES,
                              default=STATUS_CHOICES.scheduled)

    objects = models.GeoManager()

    class Meta:
        verbose_name = _('party')
        verbose_name_plural = _('parties')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('parties:detail', args=[self.slug, self.pk])

    @property
    def slug(self):
        return slugify(self.name)

    def is_multiday(self):
        td = self.end_date - self.start_date
        return td.days >= 1


class PartyItem(DjangoItem):
    django_model = Party

goabase/modules/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    middle_name = models.CharField(_('middle name'), max_length=30, blank=True)

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

goabase/parties/models.py
from django.contrib.gis.db import models
from django.utils.translation import ugettext_lazy as _


class Party(models.Model):
    name = models.CharField(_('name'), max_length=100)
    start_date = models.DateTimeField(_('start date'))
    end_date = models.DateTimeField(_('end date'))

    TYPE_CHOICES = (
        ('festival', _('Festival')),
        ('openair', _('Open air')),
        ('indoor', _('Indoor')),
        ('club', _('Club')),
        ('indoor_outdoor', _('In- and outdoor')),
    )
    type = models.CharField(_('type'), max_length=14, default='indoor')

    town = models.CharField(_('town'), max_length=100)
    location = models.PointField(_('location'))
    lineup = models.TextField(_('lineup'))
    decoration = models.TextField(_('decoration'))
    entry_fee = models.TextField(_('entry fee'))
    more = models.TextField(_('more'))
    organizer_name = models.CharField(_('organizer name'), max_length=255)
    organizer_text = models.TextField(_('organizer text'))
    organizer_url = models.TextField(_('organizer URL'))
    image = models.ImageField(_('image'), upload_to='uploads/%Y/%m/%d/')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    STATUS_CHOICES = (
        ('scheduled', _('Scheduled')),
        ('cancelled', _('Cancelled')),
        ('postponed', _('Postponed')),
        ('moved', _('Moved')),
    )
    status = models.CharField(_('status'), max_length=9, choices=STATUS_CHOICES,
                              default='scheduled')

    objects = models.GeoManager()

    class Meta:
        verbose_name = _('party')
        verbose_name_plural = _('parties')

    def __str__(self):
        return self.name

goabase/modules/accounts/forms.py
from allauth.account.forms import LoginForm as BaseLoginForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from django.utils.translation import ugettext_lazy as _


class LoginForm(BaseLoginForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Field('login', css_class='form-control-lg', placeholder=_('Username')),
            Field('password', css_class='form-control-lg', placeholder=_('Password')),
        )

goabase/modules/parties/views.py
from django.contrib.staticfiles.finders import find
from django.http.response import HttpResponsePermanentRedirect
from django.urls import reverse
from django.utils import timezone
from django.views.generic import DetailView, ListView

from goabase.modules.parties.models import Party


class PartyDetailView(DetailView):
    model = Party

    def get(self, request, *args, **kwargs):
        self.object = obj = self.get_object()
        correct_url = reverse('parties:detail', args=[obj.slug, obj.pk])
        if request.path != correct_url:
            return HttpResponsePermanentRedirect(correct_url)

        context = self.get_context_data(object=obj)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(PartyDetailView, self).get_context_data(**kwargs)
        td = self.object.start_date - timezone.now()
        context['react_countdown_milliseconds'] = int(td.total_seconds() * 1000)
        return context


class PartyListView(ListView):
    def get_queryset(self):
        return Party.objects.filter(start_date__gte=timezone.now()).order_by('-start_date')

goabase/modules/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from goabase.modules.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail', kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['first_name', 'middle_name', 'last_name']
    model = User

    def get_success_url(self):
        # Send the user back to their own page after a successful update
        return reverse('users:detail', kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'

goabase/templates/base.html
{% load render_bundle from webpack_loader %}
{% load webpack_static from webpack_loader %}
{% load i18n %}
<!doctype html>
<html lang="{{ LANGUAGE_CODE|slice:':2' }}">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <title>{% block meta_title %}Goanaut{% endblock %}</title>
        <meta name="description" content="{% block meta_description %}{% trans 'Platform for Goa and Psytrance parties and festivals' %}{% endblock %}" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="apple-touch-icon" href="apple-touch-icon.png" />

        {% render_bundle "main" "css" %}
        <link type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Alike&subset=latin-ext" rel="stylesheet" />
    </head>
    <body class="page">

        <header id="header" class="header{% if user.is_authenticated %} header-logged-in{% endif %}" role="banner">
            <div class="navbar navbar-toggleable-sm navbar-inverse bg-inverse">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header-collapse" aria-controls="header-collapse" aria-expanded="false" aria-label="{% trans 'Toggle navigation' %}">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="#"><b>&#2384;</b> Goanaut</a>
                <nav class="collapse navbar-collapse" id="header-collapse">
                    <ul class="nav navbar-nav mx-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <svg class="icon icon-star" width="20" height="20" aria-hidden="true"><use xlink:href="#icon-star" /></svg>
                                {% trans "Events" %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <svg class="icon icon-pencil" width="20" height="20" aria-hidden="true"><use xlink:href="#icon-pencil" /></svg>
                                {% trans "Blog" %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <svg class="icon icon-question-circle" width="20" height="20" aria-hidden="true"><use xlink:href="#icon-question-circle" /></svg>
                                {% trans "Help" %}
                            </a>
                        </li>
                    </ul>
                    <div class="navbar-right">
                        <div class="navbar-submit">
                            <a class="btn btn-outline-navbar" href="#" role="button">{% trans "Submit your event" %}</a>
                        </div>
                        <ul class="nav navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="/accounts/login/" data-login-modal>
                                    <svg class="icon icon-lock" width="20" height="20" aria-hidden="true"><use xlink:href="#icon-lock" /></svg>
                                    {% trans "Login" %}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/accounts/signup/" data-signup-modal>
                                    <svg class="icon icon-lock" width="20" height="20" aria-hidden="true"><use xlink:href="#icon-lock" /></svg>
                                    {% trans "Signup" %}
                                </a>
                            </li>
                        </ul>
                        <form class="form-inline navbar-search">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="{% trans 'Search' %}" />
                                <span class="input-group-btn">
                                    <button class="btn btn-outline-primary" type="submit">
                                        <svg class="icon icon-magnifier" width="20" height="20" aria-hidden="true"><use xlink:href="#icon-magnifier" /></svg>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </nav>
            </div>
        </header>

        <div id="content" class="page-content">
            {% block content %}{% endblock %}
        </div>

        <div style="height: 0; width: 0; position: absolute; visibility: hidden;">
            {% include "icons.svg" %}
        </div>

        <script src="https://maps.googleapis.com/maps/api/js?v=3&key=AIzaSyBiuQK_xDqFZ99YahdloDMQMbnRAiGovsQ"></script>
        {% render_bundle "main" "js" %}

        <script>
            window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
            ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
        </script>
        <script src="https://www.google-analytics.com/analytics.js" async defer></script>
    </body>
</html>

goabase/templates/base_ajax.html
{% block content %}{% endblock %}

goabase/templates/base_modal.html
<div class="modal fade">
    <div class="modal-dialog" role="dialog">
        {% block content %}{% endblock %}
    </div>
</div>

goabase/templates/index.html
{% extends "base.html" %}
{% load el_pagination_tags i18n icon_helpers placeholder_helpers %}

{% block content %}
    <div class="map-search">
        <div class="sidenav bg-inverse" role="complementary">
            <ul class="nav sidenav-nav">
                <li class="nav-item festival">
                    <a class="nav-link" href="#">
                        {% icon 'large/festival' %}
                        {% trans "Festival" %}
                    </a>
                </li>
                <li class="nav-item openair">
                    <a class="nav-link" href="#">
                        {% icon 'large/open-air' %}
                        {% trans "Open Air" %}
                    </a>
                </li>
                <li class="nav-item indoor">
                    <a class="nav-link" href="#">
                        {% icon 'large/party' %}
                        {% trans "Indoor" %}
                    </a>
                </li>
                <li class="nav-item indoor-outdoor">
                    <a class="nav-link" href="#">
                        {% icon 'large/seasonal' %}
                        {% trans "In- & Outdoor" %}
                    </a>
                </li>
                <li class="nav-item club">
                    <a class="nav-link" href="#">
                        {% icon 'large/club' %}
                        {% trans "Club" %}
                    </a>
                </li>
                <li class="nav-item active all-events">
                    <a class="nav-link" href="#">
                        {% blocktrans %}All<br>events{% endblocktrans %}
                    </a>
                </li>
            </ul>
        </div>
        <div class="content">
            <div class="content-header">
                <h2>{% trans "All events" %}</h2>
                <form class="filters">
                    <div class="filters-section form-group row">
                        <label for="filter_type" class="col-sm-3 col-form-label">{% trans "Type" %}:</label>
                        <div class="col-sm-9">
                            <select class="custom-select" id="filter_type">
                                <option>{% trans "Any type" %}</option>
                            </select>
                        </div>
                    </div>
                    <div class="filters-section form-group row">
                        <label for="filter_price" class="col-sm-3 col-form-label">{% trans "Price range" %}:</label>
                        <div class="col-sm-9">
                            <div class="custom-slider">
                                <input type="text" class="custom-slider-input" id="filter_price" data-slider-id="filterPriceSlider" data-slider-min="0" data-slider-max="100" data-slider-step="1" data-slider-value="[5,25]" />
                            </div>
                        </div>
                    </div>
                    <div class="filters-section form-group row">
                        <label for="filter_location" class="col-sm-3 col-form-label">{% trans "Location" %}:</label>
                        <div class="col-sm-7">
                            <input type="email" class="form-control" id="filter_location" placeholder="{% trans 'Enter location' %}" />
                        </div>
                        <div class="col-sm-2">
                            <label class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" />
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description">{% trans "Near me" %}</span>
                            </label>
                        </div>
                    </div>
                    <div class="filters-section form-group row">
                        <label for="filter_order" class="col-sm-3 col-form-label">{% trans "Sorting by" %}:</label>
                        <div class="col-sm-9">
                            <select class="custom-select" id="filter_order">
                                <option>{% trans "Popular" %}</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="content-body map-search-results">
                <div class="parties-container">
                    <div class="card-deck party-card-deck">
                        {% paginate 40 party_list %}
                        {% for party in party_list %}
                            <div class="card party-card" data-location='{"lat": {{ party.location.1 }}, "lng": {{ party.location.0 }}}' data-type="{{ party.type }}" itemscope itemtype="http://schema.org/Event">
                                <a class="party-card-img-wrapper" href="{% url 'parties:detail' party.slug party.id %}">
                                    <img class="card-img" src="{% placeholder_image 'images/placeholders/' %}" alt="{{ party.name }}" itemprop="image" />
                                </a>
                                <div class="card-img-overlay">
                                    <div class="party-card-date">
                                        <em>{{ party.start_date|date:"M" }}</em>
                                        {{ party.start_date|date:"d" }}
                                    </div>
                                    {% if "days" not in party.end_date|timeuntil:party.start_date %}
                                        <p class="party-card-time">{{ party.start_date|date:"H:i" }} - {{ party.end_date|date:"H:i" }}</p>
                                    {% endif %}
                                    <div class="party-card-favorite float-right">
                                        <a href="#">
                                            <svg class="icon icon-heart" width="20" height="20" aria-hidden="true"><use xlink:href="#icon-heart" /></svg>
                                            <svg class="icon icon-heart-filled" width="20" height="20" aria-hidden="true"><use xlink:href="#icon-heart-filled" /></svg>
                                        </a>
                                    </div>
                                </div>
                                <div class="card-block">
                                    <h4 class="card-title" itemprop="name">{{ party.name }}</h4>
                                    <p class="card-text text-muted party-card-type">{{ party.get_type_display }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="map-search-results-footer">
                    <nav class="pagination-wrapper" aria-label="{% trans 'Search results pages' %}">
                        {% show_pages %}
                    </nav>
                </div>
            </div>
        </div>
        <div id="map" class="map"></div>
    </div>
{% endblock %}